/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rental_mobil;

import java.sql.*;
import java.text.*;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class daftarmobil extends javax.swing.JFrame {
    
    Connection Con;
    ResultSet RsMobil;
    Statement stm;
    String pinjam;

    /**
     * Creates new form daftarmobil
     */
    public daftarmobil() {
        initComponents();
        open_db();
        kosong_mobil();
        kodemobil.setEditable(false);
        typemobil.setEditable(false);
        platnomer.setEditable(false);
        harga.setEditable(false);
        idpinjam.setEnabled(false);
        tglpinjam.setDate(new Date());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        agya = new javax.swing.JButton();
        livina = new javax.swing.JButton();
        jazz = new javax.swing.JButton();
        avanza = new javax.swing.JButton();
        apv = new javax.swing.JButton();
        innova = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        kodemobil = new javax.swing.JTextField();
        typemobil = new javax.swing.JTextField();
        platnomer = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        namapenyewa = new javax.swing.JTextField();
        nik = new javax.swing.JTextField();
        lamapinjem = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        harga = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        hitungtarif = new javax.swing.JButton();
        tarif = new javax.swing.JTextField();
        simpan = new javax.swing.JButton();
        keluar = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        hp = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        alamat = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        idpinjam = new javax.swing.JTextField();
        tglpinjam = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("orange juice", 1, 36)); // NOI18N
        jLabel1.setText("Form Peminjaman");

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));

        agya.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rental_mobil/agya.jpg"))); // NOI18N
        agya.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agyaActionPerformed(evt);
            }
        });

        livina.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rental_mobil/livina.jpg"))); // NOI18N
        livina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                livinaActionPerformed(evt);
            }
        });

        jazz.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rental_mobil/jazz.jpg"))); // NOI18N
        jazz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jazzActionPerformed(evt);
            }
        });

        avanza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rental_mobil/avanza.jpeg"))); // NOI18N
        avanza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                avanzaActionPerformed(evt);
            }
        });

        apv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rental_mobil/apv.jpg"))); // NOI18N
        apv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apvActionPerformed(evt);
            }
        });

        innova.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rental_mobil/innova.jpg"))); // NOI18N
        innova.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                innovaActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Kode Mobil");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Type Mobil");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Nomer Polisi");

        kodemobil.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        typemobil.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        platnomer.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Nama Peminjam");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("NIK");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Lama Pinjam");

        namapenyewa.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        nik.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        lamapinjem.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Harga");

        harga.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("12 Jam");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Jam");

        hitungtarif.setText("Tarif Sewa");
        hitungtarif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitungtarifActionPerformed(evt);
            }
        });

        tarif.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        simpan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        simpan.setText("Simpan");
        simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanActionPerformed(evt);
            }
        });

        keluar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        keluar.setText("Keluar");
        keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Tanggal Pinjam");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Nomer Telpon");

        hp.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Alamat");

        alamat.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("ID Pinjam");

        idpinjam.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jSeparator1)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(avanza, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(agya, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(420, 420, 420)
                                .addComponent(innova, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(apv, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(94, 94, 94)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(livina, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jazz, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(305, 305, 305))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel8))
                                        .addGap(50, 50, 50)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(typemobil)
                                            .addComponent(platnomer)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(harga, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel9))
                                            .addComponent(kodemobil, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addGap(30, 30, 30)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(idpinjam, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tglpinjam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lamapinjem, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel10))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(hp, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel6))
                                        .addGap(54, 54, 54)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(nik, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(namapenyewa, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(alamat, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(441, 441, 441)
                                .addComponent(hitungtarif)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tarif, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(86, 86, 86)
                                .addComponent(keluar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(24, 121, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(409, 409, 409))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(innova, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(livina, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, Short.MAX_VALUE)))
                    .addComponent(agya))
                .addGap(58, 58, 58)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(avanza, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jazz)
                    .addComponent(apv, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(kodemobil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(typemobil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(platnomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(harga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel13)
                            .addComponent(alamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(namapenyewa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(nik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(hp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(lamapinjem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(hitungtarif)
                            .addComponent(tarif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11)
                            .addComponent(tglpinjam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(idpinjam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))))
                .addGap(74, 74, 74)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(keluar, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void livinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_livinaActionPerformed
        // TODO add your handling code here:
        String status;
        try {
            kosong_mobil();
            String Mobil = "Grand Livina";
            stm = Con.createStatement();
            RsMobil = stm.executeQuery("select * from mobil where type = '"+Mobil+"'");
            RsMobil.beforeFirst();
            while(RsMobil.next()) {
                status = RsMobil.getString("status");
                if("Rusak".equals(status)){
                    JOptionPane.showMessageDialog(null, "Mobil Sedang Service");
                }
                else{
                    kodemobil.setText(RsMobil.getString("idm"));
                    typemobil.setText(RsMobil.getString("type"));
                    platnomer.setText(RsMobil.getString("plat"));
                    harga.setText(RsMobil.getString("harga"));
                }
            }
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_livinaActionPerformed

    private void agyaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agyaActionPerformed
        // TODO add your handling code here:
        String status;
        try {
            kosong_mobil();
            String Mobil = "Toyota Agya";
            stm = Con.createStatement();
            RsMobil = stm.executeQuery("select * from mobil where type = '"+Mobil+"'");
            RsMobil.beforeFirst();
            while(RsMobil.next()) {
                status = RsMobil.getString("status");
                if("Rusak".equals(status)){
                    JOptionPane.showMessageDialog(null, "Mobil Sedang Service");
                }
                else{
                    kodemobil.setText(RsMobil.getString("idm"));
                    typemobil.setText(RsMobil.getString("type"));
                    platnomer.setText(RsMobil.getString("plat"));
                    harga.setText(RsMobil.getString("harga"));
                }
            }
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_agyaActionPerformed

    private void innovaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_innovaActionPerformed
        // TODO add your handling code here:
        String status;
        try {
            kosong_mobil();
            String Mobil = "Toyota Innova";
            stm = Con.createStatement();
            RsMobil = stm.executeQuery("select * from mobil where type = '"+Mobil+"'");
            RsMobil.beforeFirst();
            while(RsMobil.next()) {
                status = RsMobil.getString("status");
                if("Rusak".equals(status)){
                    JOptionPane.showMessageDialog(null, "Mobil Sedang Service");
                }
                else{
                    kodemobil.setText(RsMobil.getString("idm"));
                    typemobil.setText(RsMobil.getString("type"));
                    platnomer.setText(RsMobil.getString("plat"));
                    harga.setText(RsMobil.getString("harga"));
                }
            }
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_innovaActionPerformed

    private void apvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apvActionPerformed
        // TODO add your handling code here:
        String status;
        try {
            kosong_mobil();
            String Mobil = "Suzuki APV";
            stm = Con.createStatement();
            RsMobil = stm.executeQuery("select * from mobil where type = '"+Mobil+"'");
            RsMobil.beforeFirst();
            while(RsMobil.next()) {
                status = RsMobil.getString("status");
                if("Rusak".equals(status)){
                    JOptionPane.showMessageDialog(null, "Mobil Sedang Service");
                }
                else{
                    kodemobil.setText(RsMobil.getString("idm"));
                    typemobil.setText(RsMobil.getString("type"));
                    platnomer.setText(RsMobil.getString("plat"));
                    harga.setText(RsMobil.getString("harga"));
                }
            }
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_apvActionPerformed

    private void jazzActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jazzActionPerformed
        // TODO add your handling code here:
        String status;
        try {
            kosong_mobil();
            String Mobil = "Honda Jazz";
            stm = Con.createStatement();
            RsMobil = stm.executeQuery("select * from mobil where type = '"+Mobil+"'");
            RsMobil.beforeFirst();
            while(RsMobil.next()) {
                status = RsMobil.getString("status");
                if("Rusak".equals(status)){
                    JOptionPane.showMessageDialog(null, "Mobil Sedang Service");
                }
                else{
                    kodemobil.setText(RsMobil.getString("idm"));
                    typemobil.setText(RsMobil.getString("type"));
                    platnomer.setText(RsMobil.getString("plat"));
                    harga.setText(RsMobil.getString("harga"));
                }
            }
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jazzActionPerformed

    private void avanzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_avanzaActionPerformed
        // TODO add your handling code here:
        String status;
        try {
            kosong_mobil();
            String Mobil = "Toyota Avanza";
            stm = Con.createStatement();
            RsMobil = stm.executeQuery("select * from mobil where type = '"+Mobil+"'");
            RsMobil.beforeFirst();
            while(RsMobil.next()) {
                status = RsMobil.getString("status");
                if("Rusak".equals(status)){
                    JOptionPane.showMessageDialog(null, "Mobil Sedang Service");
                }
                else{
                    kodemobil.setText(RsMobil.getString("idm"));
                    typemobil.setText(RsMobil.getString("type"));
                    platnomer.setText(RsMobil.getString("plat"));
                    harga.setText(RsMobil.getString("harga"));
                }
            }
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_avanzaActionPerformed

    private void hitungtarifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitungtarifActionPerformed
        // TODO add your handling code here:
        int lebih;
        int total = Integer.parseInt(lamapinjem.getText());
        
        if(total <= 12){tarif.setText(harga.getText());}
        else {
            lebih = total - 12;
            total = (Integer.parseInt(harga.getText())) + (lebih*40000);
            String hasil = Integer.toString(total);
            tarif.setText(hasil);
        };
    }//GEN-LAST:event_hitungtarifActionPerformed

    private void simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanActionPerformed
        // TODO add your handling code here:
        int Kodepinjam = 0;
        int lama = Integer.parseInt(lamapinjem.getText());
        int harga = Integer.parseInt(tarif.getText());
        int mobil = Integer.parseInt(kodemobil.getText());
        SimpleDateFormat formattgl = new SimpleDateFormat("yyyy-MM-dd");
        pinjam = formattgl.format(tglpinjam.getDate());
        String booking = "Dipinjam";
        String status = null;
        
     
        try {
            stm = Con.createStatement();
            RsMobil = stm.executeQuery("select * from mobil where idm = "+mobil+"");
            RsMobil.beforeFirst();
            while(RsMobil.next()) {
                status = RsMobil.getString("mobil.status");
            }
            
            if("Dipinjam".equals(status)){JOptionPane.showMessageDialog(null, "Mobil Sedang Dipinjam");}
            else{
                    stm.executeUpdate("INSERT into pelanggan VALUES("+nik.getText()+",'"+namapenyewa.getText()+"','"+alamat.getText()+"',"+hp.getText()+")");
                    stm.executeUpdate("INSERT into pinjam VALUES("+Kodepinjam+",'"+pinjam+"','"+nik.getText()+"',"+lama+","+harga+","+mobil+")");
                    stm.executeUpdate("Update mobil set status = '"+booking+"' where idm = "+mobil+"");
                    kosong();
                    kosong_mobil();
                    JOptionPane.showMessageDialog(null, "Berhasil di Update");
            }
        } catch (SQLException ex) {
            Logger.getLogger(daftarmobil.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_simpanActionPerformed

    private void keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarActionPerformed
        // TODO add your handling code here:
        dispose();
        new menu().setVisible(true);
    }//GEN-LAST:event_keluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(daftarmobil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(daftarmobil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(daftarmobil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(daftarmobil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new daftarmobil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agya;
    private javax.swing.JTextField alamat;
    private javax.swing.JButton apv;
    private javax.swing.JButton avanza;
    private javax.swing.JTextField harga;
    private javax.swing.JButton hitungtarif;
    private javax.swing.JTextField hp;
    private javax.swing.JTextField idpinjam;
    private javax.swing.JButton innova;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton jazz;
    private javax.swing.JButton keluar;
    private javax.swing.JTextField kodemobil;
    private javax.swing.JTextField lamapinjem;
    private javax.swing.JButton livina;
    private javax.swing.JTextField namapenyewa;
    private javax.swing.JTextField nik;
    private javax.swing.JTextField platnomer;
    private javax.swing.JButton simpan;
    private javax.swing.JTextField tarif;
    private com.toedter.calendar.JDateChooser tglpinjam;
    private javax.swing.JTextField typemobil;
    // End of variables declaration//GEN-END:variables

    private void kosong_mobil() {
        kodemobil.setText("-");
        typemobil.setText("-");
        platnomer.setText("-");
        harga.setText("-");
    }

    private void open_db() {
        try{
            KoneksiMysql kon = new KoneksiMysql ("localhost","root","","pinjammobil");
            Con = kon.getConnection();
        }catch (Exception e) {
            System.out.println("Error : "+e);
        }
    }

    private void kosong() {
        idpinjam.setText("");
        namapenyewa.setText("");
        nik.setText("");
        hp.setText("");
        alamat.setText("");
        lamapinjem.setText("");
        tarif.setText("");
    }
}
